USE sakila;


#List the number of films per category.
SELECT name, COUNT(TITLE)
from film
INNER JOIN film_category
ON film_category.film_id=film.film_id
INNER JOIN category
ON category.category_id=film_category.category_id
GROUP BY name;

#Retrieve the store ID, city, and country for each store.

SELECT city, country, store_id
FROM city
INNER JOIN country
ON city.country_id=country.country_id
INNER JOIN address
ON address.city_id=city.city_id
INNER JOIN store
ON store.address_id=address.address_id;

#3. Calculate the total revenue generated by each store in dollars.

SELECT store.store_id, SUM(amount)
FROM payment
INNER JOIN staff
ON payment.staff_id=staff.staff_id
INNER JOIN store
ON store.store_id=staff.store_id
GROUP BY store_id;

#4.Determine the average running time of films for each category.

SELECT AVG(length), name
FROM film
INNER JOIN film_category
ON film.film_id=film_category.film_id
INNER JOIN category
ON category.category_id=film_category.category_id
GROUP BY name;

#5.Identify the film categories with the longest average running time.
SELECT AVG(length) as avg_length, name
FROM film
INNER JOIN film_category
ON film.film_id=film_category.film_id
INNER JOIN category
ON category.category_id=film_category.category_id
GROUP BY name
ORDER BY avg_length DESC;


SELECT DISTINCT title,
CASE 
WHEN ISNULL(inventory_id) THEN "Not Available"
ELSE "Available"
END AS status_film
FROM film
LEFT JOIN inventory
ON film.film_id=inventory.film_id;

SELECT *
FROM inventory;